### ISSUE TITLE
api_grove.js being included in all projects

### ISSUE THREAD

**Issue by tripflex** [mongoose-os-libs/mjs#5]
Why is it that the `api_grove.js` file is being loaded into any filesystem using mjs?  Shouldn't this be it's own separate file or library somewhere else outside of mjs ... feels like all this does is add extra bloat to mjs, when there is already super limited space available on embedded devices...

**Update:**
For anybody else wanting to remove specific files during build, here's how to do it in `mos.yml` project file:

```yml
conds:
  - when: mos.platform == "esp32"
    apply:
      filesystem:
        - -mjs/fs/api_grove.js
```

For removing files from mjs module (or mongoose), would be something like this:
`- -${mos.modules.mjs_module.path}/mjs/lib/api_dataview.js`

Example:
https://github.com/mongoose-os-libs/mjs/blob/master/mos_esp8266.yml
